services:
  client:
    build:
      context: ./
      target: client-dev
    container_name: anime-client
    ports:
      - "5173:5173"

  server:
    depends_on:
      - mysqldb
    build:
      context: ./
      target: server-dev
    container_name: anime-server
    restart: always
    env_file: ./server/.env
    ports:
      - "8081:8080"

  mysqldb:
    image: mysql:5.7
    container_name: anime-mysqldb
    restart: always
    env_file: ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=anime_db
    ports:
      - "3308:3306"
    volumes:
      - db_mysql:/var/lib/mysql

volumes:
  db_mysql: